name: Deploy Sphinx documentation to Pages

on:
  push:
    tags:
      - 'v*'

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    env:
      BUILD_DOCUMENT: "1"
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
    - run: |
        cp -f recis/__info__.py recis/info.py
        cp -r recis docs/
        sed -i 's/__RECIS_INTERNAL_VERSION__/0/g' recis/info.py
        rm -rf pyproject.toml
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        python_version: 3.12
        checkout: false
